build/hw/intermediate/TbSoc.bo: test_soc/TbSoc.bsv build/hw/intermediate/Soc.bo /opt/tools/bsc/latest//lib/Libraries/Clocks.bo /opt/tools/bsc/latest//lib/Libraries/GetPut.bo build/hw/intermediate/Semi_FIFOF.bo build/hw/intermediate/AXI4_Types.bo build/hw/intermediate/AXI4_Fabric.bo build/hw/intermediate/uart.bo build/hw/intermediate/ccore_types.bo build/hw/intermediate/csr_types.bo build/hw/intermediate/csrbox_decoder.bo build/hw/intermediate/csrbox.bo /opt/tools/bsc/latest//lib/Libraries/Vector.bo build/hw/intermediate/device_common.bo /opt/tools/bsc/latest//lib/Libraries/DReg.bo /opt/tools/bsc/latest//lib/Libraries/Connectable.bo build/hw/intermediate/DebugSoc.bo /opt/tools/bsc/latest//lib/Libraries/Prelude.bo /opt/tools/bsc/latest//lib/Libraries/PreludeBSV.bo csrbox_bsv//csr_probe.bsv csrbox_bsv//csrbox.defines test_soc//Soc.defines common_bsv//Logger.bsv src//ccore_params.defines
build/hw/intermediate/Soc.bo: test_soc//Soc.bsv build/hw/intermediate/Semi_FIFOF.bo build/hw/intermediate/AXI4_Types.bo build/hw/intermediate/AXI4_Fabric.bo build/hw/intermediate/ccore.bo build/hw/intermediate/ccore_types.bo /opt/tools/bsc/latest//lib/Libraries/Clocks.bo build/hw/intermediate/uart.bo build/hw/intermediate/clint.bo build/hw/intermediate/sign_dump.bo build/hw/intermediate/err_slave.bo /opt/tools/bsc/latest//lib/Libraries/Connectable.bo /opt/tools/bsc/latest//lib/Libraries/GetPut.bo /opt/tools/bsc/latest//lib/Libraries/Vector.bo build/hw/intermediate/bram.bo build/hw/intermediate/bootrom.bo build/hw/intermediate/csrbox.bo build/hw/intermediate/debug_types.bo /opt/tools/bsc/latest//lib/Libraries/Prelude.bo /opt/tools/bsc/latest//lib/Libraries/PreludeBSV.bo test_soc//Soc.defines src//ccore_params.defines
build/hw/intermediate/Semi_FIFOF.bo: fabrics/axi4/Semi_FIFOF.bsv /opt/tools/bsc/latest//lib/Libraries/FIFOF.bo /opt/tools/bsc/latest//lib/Libraries/Connectable.bo /opt/tools/bsc/latest//lib/Libraries/Prelude.bo /opt/tools/bsc/latest//lib/Libraries/PreludeBSV.bo
build/hw/intermediate/AXI4_Types.bo: fabrics/axi4/AXI4_Types.bsv /opt/tools/bsc/latest//lib/Libraries/FIFOF.bo /opt/tools/bsc/latest//lib/Libraries/Connectable.bo build/hw/intermediate/Semi_FIFOF.bo /opt/tools/bsc/latest//lib/Libraries/Prelude.bo /opt/tools/bsc/latest//lib/Libraries/PreludeBSV.bo
build/hw/intermediate/AXI4_Fabric.bo: fabrics/axi4/AXI4_Fabric.bsv /opt/tools/bsc/latest//lib/Libraries/Vector.bo /opt/tools/bsc/latest//lib/Libraries/FIFOF.bo /opt/tools/bsc/latest//lib/Libraries/ConfigReg.bo build/hw/intermediate/Cur_Cycle.bo build/hw/intermediate/Semi_FIFOF.bo build/hw/intermediate/AXI4_Types.bo /opt/tools/bsc/latest//lib/Libraries/Prelude.bo /opt/tools/bsc/latest//lib/Libraries/PreludeBSV.bo common_bsv//Logger.bsv
build/hw/intermediate/uart.bo: devices/uart_v2/uart.bsv build/hw/intermediate/AXI4_Lite_Types.bo build/hw/intermediate/AXI4_Lite_Fabric.bo build/hw/intermediate/AXI4_Types.bo build/hw/intermediate/AXI4_Fabric.bo build/hw/intermediate/Semi_FIFOF.bo build/hw/intermediate/RS232_modified.bo /opt/tools/bsc/latest//lib/Libraries/GetPut.bo /opt/tools/bsc/latest//lib/Libraries/FIFO.bo /opt/tools/bsc/latest//lib/Libraries/Clocks.bo /opt/tools/bsc/latest//lib/Libraries/BUtils.bo build/hw/intermediate/device_common.bo build/hw/intermediate/ConcatReg.bo /opt/tools/bsc/latest//lib/Libraries/Prelude.bo /opt/tools/bsc/latest//lib/Libraries/PreludeBSV.bo devices/uart_v2/uart.defines common_bsv//Logger.bsv
build/hw/intermediate/ccore_types.bo: src//ccore_types.bsv build/hw/intermediate/csr_types.bo build/hw/intermediate/csrbox_decoder.bo /opt/tools/bsc/latest//lib/Libraries/DefaultValue.bo /opt/tools/bsc/latest//lib/Libraries/Vector.bo /opt/tools/bsc/latest//lib/Libraries/Prelude.bo /opt/tools/bsc/latest//lib/Libraries/PreludeBSV.bo src//trap.defines csrbox_bsv//csrbox.defines src//ccore_params.defines
build/hw/intermediate/csr_types.bo: csrbox_bsv//csr_types.bsv /opt/tools/bsc/latest//lib/Libraries/Prelude.bo /opt/tools/bsc/latest//lib/Libraries/PreludeBSV.bo common_bsv//Logger.bsv csrbox_bsv//csrbox.defines
build/hw/intermediate/csrbox_decoder.bo: csrbox_bsv//csrbox_decoder.bsv /opt/tools/bsc/latest//lib/Libraries/Vector.bo /opt/tools/bsc/latest//lib/Libraries/FIFOF.bo /opt/tools/bsc/latest//lib/Libraries/DReg.bo /opt/tools/bsc/latest//lib/Libraries/UniqueWrappers.bo build/hw/intermediate/ConcatReg.bo /opt/tools/bsc/latest//lib/Libraries/GetPut.bo /opt/tools/bsc/latest//lib/Libraries/Connectable.bo build/hw/intermediate/csr_types.bo /opt/tools/bsc/latest//lib/Libraries/Assert.bo /opt/tools/bsc/latest//lib/Libraries/Prelude.bo /opt/tools/bsc/latest//lib/Libraries/PreludeBSV.bo common_bsv//Logger.bsv csrbox_bsv//csrbox.defines
build/hw/intermediate/csrbox.bo: csrbox_bsv//csrbox.bsv /opt/tools/bsc/latest//lib/Libraries/Vector.bo /opt/tools/bsc/latest//lib/Libraries/FIFOF.bo /opt/tools/bsc/latest//lib/Libraries/DReg.bo /opt/tools/bsc/latest//lib/Libraries/UniqueWrappers.bo build/hw/intermediate/ConcatReg.bo /opt/tools/bsc/latest//lib/Libraries/GetPut.bo /opt/tools/bsc/latest//lib/Libraries/Connectable.bo build/hw/intermediate/csr_types.bo /opt/tools/bsc/latest//lib/Libraries/Assert.bo build/hw/intermediate/csrbox_grp1.bo build/hw/intermediate/csrbox_grp2.bo build/hw/intermediate/csrbox_decoder.bo /opt/tools/bsc/latest//lib/Libraries/Prelude.bo /opt/tools/bsc/latest//lib/Libraries/PreludeBSV.bo common_bsv//Logger.bsv csrbox_bsv//csrbox.defines
build/hw/intermediate/device_common.bo: common_bsv//device_common.bsv /opt/tools/bsc/latest//lib/Libraries/BUtils.bo /opt/tools/bsc/latest//lib/Libraries/Prelude.bo /opt/tools/bsc/latest//lib/Libraries/PreludeBSV.bo
build/hw/intermediate/DebugSoc.bo: test_soc//DebugSoc.bsv /opt/tools/bsc/latest//lib/Libraries/FIFOF.bo /opt/tools/bsc/latest//lib/Libraries/Vector.bo /opt/tools/bsc/latest//lib/Libraries/SpecialFIFOs.bo /opt/tools/bsc/latest//lib/Libraries/FIFOF.bo build/hw/intermediate/Soc.bo build/hw/intermediate/uart.bo /opt/tools/bsc/latest//lib/Libraries/GetPut.bo /opt/tools/bsc/latest//lib/Libraries/Connectable.bo build/hw/intermediate/jtagdtm.bo build/hw/intermediate/debug.bo build/hw/intermediate/debug_types.bo /opt/tools/bsc/latest//lib/Libraries/Clocks.bo build/hw/intermediate/ccore_types.bo build/hw/intermediate/csrbox.bo /opt/tools/bsc/latest//lib/Libraries/DefaultValue.bo /opt/tools/bsc/latest//lib/Libraries/Prelude.bo /opt/tools/bsc/latest//lib/Libraries/PreludeBSV.bo test_soc//Soc.defines common_bsv//Logger.bsv
build/hw/intermediate/ccore.bo: src//ccore.bsv build/hw/intermediate/Semi_FIFOF.bo build/hw/intermediate/AXI4_Types.bo build/hw/intermediate/AXI4_Fabric.bo build/hw/intermediate/riscv.bo build/hw/intermediate/ccore_types.bo /opt/tools/bsc/latest//lib/Libraries/FIFOF.bo build/hw/intermediate/dcache_types.bo build/hw/intermediate/icache_types.bo /opt/tools/bsc/latest//lib/Libraries/Assert.bo build/hw/intermediate/imem.bo build/hw/intermediate/dmem.bo build/hw/intermediate/pipe_ifcs.bo build/hw/intermediate/ptwalk_merged.bo /opt/tools/bsc/latest//lib/Libraries/Connectable.bo /opt/tools/bsc/latest//lib/Libraries/GetPut.bo /opt/tools/bsc/latest//lib/Libraries/BUtils.bo build/hw/intermediate/csrbox.bo build/hw/intermediate/debug_types.bo build/hw/intermediate/csr_types.bo /opt/tools/bsc/latest//lib/Libraries/Prelude.bo /opt/tools/bsc/latest//lib/Libraries/PreludeBSV.bo common_bsv//Logger.bsv src//ccore_params.defines
build/hw/intermediate/clint.bo: devices/clint/clint.bsv /opt/tools/bsc/latest//lib/Libraries/ConfigReg.bo build/hw/intermediate/Semi_FIFOF.bo build/hw/intermediate/AXI4_Lite_Types.bo build/hw/intermediate/AXI4_Types.bo /opt/tools/bsc/latest//lib/Libraries/BUtils.bo build/hw/intermediate/device_common.bo /opt/tools/bsc/latest//lib/Libraries/GetPut.bo /opt/tools/bsc/latest//lib/Libraries/Assert.bo /opt/tools/bsc/latest//lib/Libraries/Prelude.bo /opt/tools/bsc/latest//lib/Libraries/PreludeBSV.bo common_bsv//Logger.bsv devices/clint/clint.defines
build/hw/intermediate/sign_dump.bo: test_soc//sign_dump.bsv /opt/tools/bsc/latest//lib/Libraries/Vector.bo /opt/tools/bsc/latest//lib/Libraries/FIFOF.bo /opt/tools/bsc/latest//lib/Libraries/DReg.bo /opt/tools/bsc/latest//lib/Libraries/SpecialFIFOs.bo /opt/tools/bsc/latest//lib/Libraries/BRAMCore.bo /opt/tools/bsc/latest//lib/Libraries/FIFO.bo build/hw/intermediate/ccore_types.bo build/hw/intermediate/AXI4_Types.bo build/hw/intermediate/AXI4_Fabric.bo build/hw/intermediate/Semi_FIFOF.bo /opt/tools/bsc/latest//lib/Libraries/Prelude.bo /opt/tools/bsc/latest//lib/Libraries/PreludeBSV.bo src//ccore_params.defines
build/hw/intermediate/err_slave.bo: devices/err_slave/err_slave.bsv /opt/tools/bsc/latest//lib/Libraries/Vector.bo /opt/tools/bsc/latest//lib/Libraries/FIFOF.bo /opt/tools/bsc/latest//lib/Libraries/DReg.bo /opt/tools/bsc/latest//lib/Libraries/SpecialFIFOs.bo /opt/tools/bsc/latest//lib/Libraries/BRAMCore.bo /opt/tools/bsc/latest//lib/Libraries/FIFO.bo build/hw/intermediate/AXI4_Types.bo build/hw/intermediate/AXI4_Fabric.bo build/hw/intermediate/AXI4_Lite_Types.bo build/hw/intermediate/AXI4_Lite_Fabric.bo build/hw/intermediate/Semi_FIFOF.bo /opt/tools/bsc/latest//lib/Libraries/Prelude.bo /opt/tools/bsc/latest//lib/Libraries/PreludeBSV.bo
build/hw/intermediate/bram.bo: devices/bram/bram.bsv /opt/tools/bsc/latest//lib/Libraries/BRAMCore.bo /opt/tools/bsc/latest//lib/Libraries/DReg.bo build/hw/intermediate/Semi_FIFOF.bo build/hw/intermediate/AXI4_Types.bo build/hw/intermediate/AXI4_Fabric.bo build/hw/intermediate/AXI4_Lite_Types.bo build/hw/intermediate/AXI4_Lite_Fabric.bo /opt/tools/bsc/latest//lib/Libraries/BUtils.bo /opt/tools/bsc/latest//lib/Libraries/GetPut.bo build/hw/intermediate/device_common.bo /opt/tools/bsc/latest//lib/Libraries/Assert.bo /opt/tools/bsc/latest//lib/Libraries/Prelude.bo /opt/tools/bsc/latest//lib/Libraries/PreludeBSV.bo common_bsv//Logger.bsv
build/hw/intermediate/bootrom.bo: devices/bootrom/bootrom.bsv /opt/tools/bsc/latest//lib/Libraries/BRAMCore.bo /opt/tools/bsc/latest//lib/Libraries/DReg.bo build/hw/intermediate/Semi_FIFOF.bo build/hw/intermediate/AXI4_Types.bo build/hw/intermediate/AXI4_Fabric.bo build/hw/intermediate/AXI4_Lite_Types.bo build/hw/intermediate/AXI4_Lite_Fabric.bo /opt/tools/bsc/latest//lib/Libraries/BUtils.bo /opt/tools/bsc/latest//lib/Libraries/GetPut.bo build/hw/intermediate/device_common.bo /opt/tools/bsc/latest//lib/Libraries/Prelude.bo /opt/tools/bsc/latest//lib/Libraries/PreludeBSV.bo common_bsv//Logger.bsv
build/hw/intermediate/debug_types.bo: devices/riscvdebug100/debug_types.bsv /opt/tools/bsc/latest//lib/Libraries/FIFOF.bo /opt/tools/bsc/latest//lib/Libraries/Vector.bo /opt/tools/bsc/latest//lib/Libraries/SpecialFIFOs.bo /opt/tools/bsc/latest//lib/Libraries/FIFOF.bo /opt/tools/bsc/latest//lib/Libraries/DefaultValue.bo /opt/tools/bsc/latest//lib/Libraries/Reserved.bo /opt/tools/bsc/latest//lib/Libraries/Vector.bo build/hw/intermediate/AXI4_Types.bo build/hw/intermediate/AXI4_Lite_Types.bo /opt/tools/bsc/latest//lib/Libraries/GetPut.bo /opt/tools/bsc/latest//lib/Libraries/Prelude.bo /opt/tools/bsc/latest//lib/Libraries/PreludeBSV.bo devices/riscvdebug100/debug.defines
build/hw/intermediate/Cur_Cycle.bo: fabrics/axi4/Cur_Cycle.bsv /opt/tools/bsc/latest//lib/Libraries/Prelude.bo /opt/tools/bsc/latest//lib/Libraries/PreludeBSV.bo
build/hw/intermediate/AXI4_Lite_Types.bo: fabrics/axi4lite/AXI4_Lite_Types.bsv /opt/tools/bsc/latest//lib/Libraries/FIFOF.bo /opt/tools/bsc/latest//lib/Libraries/Connectable.bo build/hw/intermediate/Semi_FIFOF.bo /opt/tools/bsc/latest//lib/Libraries/Prelude.bo /opt/tools/bsc/latest//lib/Libraries/PreludeBSV.bo
build/hw/intermediate/AXI4_Lite_Fabric.bo: fabrics/axi4lite/AXI4_Lite_Fabric.bsv /opt/tools/bsc/latest//lib/Libraries/Vector.bo /opt/tools/bsc/latest//lib/Libraries/FIFOF.bo /opt/tools/bsc/latest//lib/Libraries/ConfigReg.bo build/hw/intermediate/Cur_Cycle.bo build/hw/intermediate/Semi_FIFOF.bo build/hw/intermediate/AXI4_Lite_Types.bo /opt/tools/bsc/latest//lib/Libraries/Prelude.bo /opt/tools/bsc/latest//lib/Libraries/PreludeBSV.bo common_bsv//Logger.bsv
build/hw/intermediate/RS232_modified.bo: devices/uart_v2/RS232_modified.bsv /opt/tools/bsc/latest//lib/Libraries/Clocks.bo /opt/tools/bsc/latest//lib/Libraries/GetPut.bo /opt/tools/bsc/latest//lib/Libraries/Connectable.bo /opt/tools/bsc/latest//lib/Libraries/FIFOLevel.bo /opt/tools/bsc/latest//lib/Libraries/Vector.bo /opt/tools/bsc/latest//lib/Libraries/BUtils.bo /opt/tools/bsc/latest//lib/Libraries/Counter.bo build/hw/intermediate/ConcatReg.bo /opt/tools/bsc/latest//lib/Libraries/ConfigReg.bo /opt/tools/bsc/latest//lib/Libraries/Prelude.bo /opt/tools/bsc/latest//lib/Libraries/PreludeBSV.bo
build/hw/intermediate/ConcatReg.bo: common_bsv//ConcatReg.bsv /opt/tools/bsc/latest//lib/Libraries/Prelude.bo /opt/tools/bsc/latest//lib/Libraries/PreludeBSV.bo
build/hw/intermediate/csrbox_grp1.bo: csrbox_bsv//csrbox_grp1.bsv /opt/tools/bsc/latest//lib/Libraries/Vector.bo /opt/tools/bsc/latest//lib/Libraries/FIFOF.bo /opt/tools/bsc/latest//lib/Libraries/DReg.bo /opt/tools/bsc/latest//lib/Libraries/UniqueWrappers.bo build/hw/intermediate/ConcatReg.bo /opt/tools/bsc/latest//lib/Libraries/GetPut.bo /opt/tools/bsc/latest//lib/Libraries/Connectable.bo build/hw/intermediate/csr_types.bo /opt/tools/bsc/latest//lib/Libraries/Assert.bo /opt/tools/bsc/latest//lib/Libraries/Prelude.bo /opt/tools/bsc/latest//lib/Libraries/PreludeBSV.bo common_bsv//Logger.bsv csrbox_bsv//csrbox.defines
build/hw/intermediate/csrbox_grp2.bo: csrbox_bsv//csrbox_grp2.bsv /opt/tools/bsc/latest//lib/Libraries/Vector.bo /opt/tools/bsc/latest//lib/Libraries/FIFOF.bo /opt/tools/bsc/latest//lib/Libraries/DReg.bo /opt/tools/bsc/latest//lib/Libraries/UniqueWrappers.bo build/hw/intermediate/ConcatReg.bo /opt/tools/bsc/latest//lib/Libraries/GetPut.bo /opt/tools/bsc/latest//lib/Libraries/Connectable.bo build/hw/intermediate/csr_types.bo /opt/tools/bsc/latest//lib/Libraries/Assert.bo /opt/tools/bsc/latest//lib/Libraries/Prelude.bo /opt/tools/bsc/latest//lib/Libraries/PreludeBSV.bo common_bsv//Logger.bsv csrbox_bsv//csrbox.defines
build/hw/intermediate/jtagdtm.bo: devices/jtagdtm//jtagdtm.bsv /opt/tools/bsc/latest//lib/Libraries/Clocks.bo build/hw/intermediate/ConcatReg.bo /opt/tools/bsc/latest//lib/Libraries/FIFO.bo /opt/tools/bsc/latest//lib/Libraries/FIFOF.bo /opt/tools/bsc/latest//lib/Libraries/SpecialFIFOs.bo /opt/tools/bsc/latest//lib/Libraries/DReg.bo /opt/tools/bsc/latest//lib/Libraries/Prelude.bo /opt/tools/bsc/latest//lib/Libraries/PreludeBSV.bo common_bsv//Logger.bsv devices/jtagdtm//jtagdefines.bsv
build/hw/intermediate/debug.bo: devices/riscvdebug100/debug.bsv /opt/tools/bsc/latest//lib/Libraries/FIFOF.bo /opt/tools/bsc/latest//lib/Libraries/Vector.bo /opt/tools/bsc/latest//lib/Libraries/SpecialFIFOs.bo /opt/tools/bsc/latest//lib/Libraries/FIFOF.bo build/hw/intermediate/ConcatReg.bo /opt/tools/bsc/latest//lib/Libraries/ConfigReg.bo /opt/tools/bsc/latest//lib/Libraries/DReg.bo /opt/tools/bsc/latest//lib/Libraries/Assert.bo /opt/tools/bsc/latest//lib/Libraries/DefaultValue.bo /opt/tools/bsc/latest//lib/Libraries/Clocks.bo /opt/tools/bsc/latest//lib/Libraries/GetPut.bo /opt/tools/bsc/latest//lib/Libraries/BUtils.bo /opt/tools/bsc/latest//lib/Libraries/Memory.bo build/hw/intermediate/AXI4_Types.bo build/hw/intermediate/AXI4_Lite_Types.bo build/hw/intermediate/Semi_FIFOF.bo build/hw/intermediate/debug_types.bo /opt/tools/bsc/latest//lib/Libraries/Prelude.bo /opt/tools/bsc/latest//lib/Libraries/PreludeBSV.bo devices/riscvdebug100/debug.defines common_bsv//Logger.bsv
build/hw/intermediate/riscv.bo: src//riscv.bsv /opt/tools/bsc/latest//lib/Libraries/FIFOF.bo /opt/tools/bsc/latest//lib/Libraries/Vector.bo /opt/tools/bsc/latest//lib/Libraries/SpecialFIFOs.bo /opt/tools/bsc/latest//lib/Libraries/FIFOF.bo /opt/tools/bsc/latest//lib/Libraries/Connectable.bo /opt/tools/bsc/latest//lib/Libraries/GetPut.bo /opt/tools/bsc/latest//lib/Libraries/DReg.bo /opt/tools/bsc/latest//lib/Libraries/Clocks.bo build/hw/intermediate/mbox.bo build/hw/intermediate/fpu.bo build/hw/intermediate/scoreboard.bo build/hw/intermediate/stage0.bo build/hw/intermediate/stage1.bo build/hw/intermediate/stage2.bo build/hw/intermediate/stage3.bo build/hw/intermediate/stage4.bo build/hw/intermediate/stage5.bo build/hw/intermediate/pipe_ifcs.bo build/hw/intermediate/ccore_types.bo build/hw/intermediate/csrbox.bo /opt/tools/bsc/latest//lib/Libraries/Prelude.bo /opt/tools/bsc/latest//lib/Libraries/PreludeBSV.bo common_bsv//Logger.bsv
build/hw/intermediate/dcache_types.bo: caches_mmu/src/dcache/dcache_types.bsv /opt/tools/bsc/latest//lib/Libraries/Prelude.bo /opt/tools/bsc/latest//lib/Libraries/PreludeBSV.bo caches_mmu/src/dcache/dcache.defines
build/hw/intermediate/icache_types.bo: caches_mmu/src/icache_1rw/icache_types.bsv /opt/tools/bsc/latest//lib/Libraries/Prelude.bo /opt/tools/bsc/latest//lib/Libraries/PreludeBSV.bo
build/hw/intermediate/imem.bo: caches_mmu/src/icache_1rw/imem.bsv /opt/tools/bsc/latest//lib/Libraries/Vector.bo /opt/tools/bsc/latest//lib/Libraries/FIFOF.bo /opt/tools/bsc/latest//lib/Libraries/DReg.bo /opt/tools/bsc/latest//lib/Libraries/SpecialFIFOs.bo /opt/tools/bsc/latest//lib/Libraries/BRAMCore.bo /opt/tools/bsc/latest//lib/Libraries/FIFO.bo /opt/tools/bsc/latest//lib/Libraries/GetPut.bo /opt/tools/bsc/latest//lib/Libraries/Connectable.bo build/hw/intermediate/icache_types.bo build/hw/intermediate/io_func.bo build/hw/intermediate/icache.bo build/hw/intermediate/fa_itlb.bo build/hw/intermediate/common_tlb_types.bo /opt/tools/bsc/latest//lib/Libraries/Prelude.bo /opt/tools/bsc/latest//lib/Libraries/PreludeBSV.bo caches_mmu/src/tlbs/common_tlb.defines caches_mmu/src/icache_1rw/icache.defines
build/hw/intermediate/dmem.bo: caches_mmu/src/dcache/dmem.bsv /opt/tools/bsc/latest//lib/Libraries/Vector.bo /opt/tools/bsc/latest//lib/Libraries/FIFOF.bo /opt/tools/bsc/latest//lib/Libraries/DReg.bo /opt/tools/bsc/latest//lib/Libraries/SpecialFIFOs.bo /opt/tools/bsc/latest//lib/Libraries/BRAMCore.bo /opt/tools/bsc/latest//lib/Libraries/FIFO.bo /opt/tools/bsc/latest//lib/Libraries/GetPut.bo /opt/tools/bsc/latest//lib/Libraries/Connectable.bo build/hw/intermediate/dcache_types.bo build/hw/intermediate/io_func.bo build/hw/intermediate/dcache1rw.bo build/hw/intermediate/fa_dtlb.bo build/hw/intermediate/common_tlb_types.bo /opt/tools/bsc/latest//lib/Libraries/Prelude.bo /opt/tools/bsc/latest//lib/Libraries/PreludeBSV.bo common_bsv//Logger.bsv caches_mmu/src/dcache/dcache.defines
build/hw/intermediate/pipe_ifcs.bo: src//pipe_ifcs.bsv /opt/tools/bsc/latest//lib/Libraries/FIFOF.bo /opt/tools/bsc/latest//lib/Libraries/Vector.bo /opt/tools/bsc/latest//lib/Libraries/SpecialFIFOs.bo /opt/tools/bsc/latest//lib/Libraries/FIFOF.bo /opt/tools/bsc/latest//lib/Libraries/GetPut.bo /opt/tools/bsc/latest//lib/Libraries/Connectable.bo build/hw/intermediate/ccore_types.bo build/hw/intermediate/dcache_types.bo build/hw/intermediate/icache_types.bo build/hw/intermediate/TxRx.bo build/hw/intermediate/mbox.bo build/hw/intermediate/csrbox.bo /opt/tools/bsc/latest//lib/Libraries/Prelude.bo /opt/tools/bsc/latest//lib/Libraries/PreludeBSV.bo common_bsv//Logger.bsv
build/hw/intermediate/ptwalk_merged.bo: caches_mmu/src/tlbs/ptwalk_merged.bsv /opt/tools/bsc/latest//lib/Libraries/Vector.bo /opt/tools/bsc/latest//lib/Libraries/FIFOF.bo /opt/tools/bsc/latest//lib/Libraries/DReg.bo /opt/tools/bsc/latest//lib/Libraries/SpecialFIFOs.bo /opt/tools/bsc/latest//lib/Libraries/BRAMCore.bo /opt/tools/bsc/latest//lib/Libraries/FIFO.bo /opt/tools/bsc/latest//lib/Libraries/GetPut.bo build/hw/intermediate/dcache_types.bo build/hw/intermediate/common_tlb_types.bo /opt/tools/bsc/latest//lib/Libraries/Prelude.bo /opt/tools/bsc/latest//lib/Libraries/PreludeBSV.bo caches_mmu/src/tlbs/common_tlb.defines common_bsv//Logger.bsv caches_mmu/src/dcache/dcache.defines
build/hw/intermediate/mbox.bo: src/mbox/mbox.bsv build/hw/intermediate/ccore_types.bo build/hw/intermediate/combo.bo build/hw/intermediate/restoring_div.bo /opt/tools/bsc/latest//lib/Libraries/SpecialFIFOs.bo /opt/tools/bsc/latest//lib/Libraries/FIFOF.bo build/hw/intermediate/TxRx.bo /opt/tools/bsc/latest//lib/Libraries/Assert.bo /opt/tools/bsc/latest//lib/Libraries/Prelude.bo /opt/tools/bsc/latest//lib/Libraries/PreludeBSV.bo common_bsv//Logger.bsv
build/hw/intermediate/fpu.bo: src/fpu//fpu.bsv build/hw/intermediate/fpu_bsvfloat.bo /opt/tools/bsc/latest//lib/Libraries/Prelude.bo /opt/tools/bsc/latest//lib/Libraries/PreludeBSV.bo
build/hw/intermediate/scoreboard.bo: src//scoreboard.bsv /opt/tools/bsc/latest//lib/Libraries/FIFOF.bo /opt/tools/bsc/latest//lib/Libraries/Vector.bo /opt/tools/bsc/latest//lib/Libraries/SpecialFIFOs.bo /opt/tools/bsc/latest//lib/Libraries/FIFOF.bo build/hw/intermediate/ccore_types.bo /opt/tools/bsc/latest//lib/Libraries/Prelude.bo /opt/tools/bsc/latest//lib/Libraries/PreludeBSV.bo common_bsv//Logger.bsv
build/hw/intermediate/stage0.bo: src//stage0.bsv /opt/tools/bsc/latest//lib/Libraries/FIFO.bo /opt/tools/bsc/latest//lib/Libraries/FIFOF.bo /opt/tools/bsc/latest//lib/Libraries/SpecialFIFOs.bo /opt/tools/bsc/latest//lib/Libraries/GetPut.bo build/hw/intermediate/TxRx.bo build/hw/intermediate/icache_types.bo build/hw/intermediate/pipe_ifcs.bo build/hw/intermediate/ccore_types.bo build/hw/intermediate/gshare_fa.bo /opt/tools/bsc/latest//lib/Libraries/Prelude.bo /opt/tools/bsc/latest//lib/Libraries/PreludeBSV.bo src//ccore_params.defines common_bsv//Logger.bsv
build/hw/intermediate/stage1.bo: src//stage1.bsv /opt/tools/bsc/latest//lib/Libraries/FIFOF.bo /opt/tools/bsc/latest//lib/Libraries/SpecialFIFOs.bo /opt/tools/bsc/latest//lib/Libraries/FIFO.bo /opt/tools/bsc/latest//lib/Libraries/GetPut.bo /opt/tools/bsc/latest//lib/Libraries/Assert.bo /opt/tools/bsc/latest//lib/Libraries/Vector.bo build/hw/intermediate/TxRx.bo build/hw/intermediate/ccore_types.bo build/hw/intermediate/icache_types.bo build/hw/intermediate/pipe_ifcs.bo build/hw/intermediate/decompress.bo /opt/tools/bsc/latest//lib/Libraries/Prelude.bo /opt/tools/bsc/latest//lib/Libraries/PreludeBSV.bo common_bsv//Logger.bsv src//ccore_params.defines
build/hw/intermediate/stage2.bo: src//stage2.bsv /opt/tools/bsc/latest//lib/Libraries/FIFOF.bo build/hw/intermediate/TxRx.bo /opt/tools/bsc/latest//lib/Libraries/DReg.bo /opt/tools/bsc/latest//lib/Libraries/Connectable.bo /opt/tools/bsc/latest//lib/Libraries/GetPut.bo /opt/tools/bsc/latest//lib/Libraries/ConfigReg.bo /opt/tools/bsc/latest//lib/Libraries/OInt.bo build/hw/intermediate/registerfile.bo build/hw/intermediate/decoder.bo build/hw/intermediate/ccore_types.bo build/hw/intermediate/pipe_ifcs.bo /opt/tools/bsc/latest//lib/Libraries/Prelude.bo /opt/tools/bsc/latest//lib/Libraries/PreludeBSV.bo common_bsv//Logger.bsv src//trap.defines src//ccore_params.defines
build/hw/intermediate/stage3.bo: src//stage3.bsv /opt/tools/bsc/latest//lib/Libraries/GetPut.bo /opt/tools/bsc/latest//lib/Libraries/FIFOF.bo /opt/tools/bsc/latest//lib/Libraries/SpecialFIFOs.bo /opt/tools/bsc/latest//lib/Libraries/DReg.bo build/hw/intermediate/TxRx.bo /opt/tools/bsc/latest//lib/Libraries/Vector.bo /opt/tools/bsc/latest//lib/Libraries/ConfigReg.bo /opt/tools/bsc/latest//lib/Libraries/Probe.bo build/hw/intermediate/base_alu.bo build/hw/intermediate/bypass.bo build/hw/intermediate/ccore_types.bo build/hw/intermediate/dcache_types.bo build/hw/intermediate/pipe_ifcs.bo build/hw/intermediate/scoreboard.bo build/hw/intermediate/mbox.bo /opt/tools/bsc/latest//lib/Libraries/Prelude.bo /opt/tools/bsc/latest//lib/Libraries/PreludeBSV.bo src//trap.defines common_bsv//Logger.bsv src//ccore_params.defines
build/hw/intermediate/stage4.bo: src//stage4.bsv /opt/tools/bsc/latest//lib/Libraries/FIFOF.bo /opt/tools/bsc/latest//lib/Libraries/Vector.bo /opt/tools/bsc/latest//lib/Libraries/SpecialFIFOs.bo /opt/tools/bsc/latest//lib/Libraries/FIFOF.bo build/hw/intermediate/TxRx.bo /opt/tools/bsc/latest//lib/Libraries/GetPut.bo build/hw/intermediate/ccore_types.bo build/hw/intermediate/dcache_types.bo build/hw/intermediate/pipe_ifcs.bo /opt/tools/bsc/latest//lib/Libraries/Prelude.bo /opt/tools/bsc/latest//lib/Libraries/PreludeBSV.bo common_bsv//Logger.bsv src//trap.defines
build/hw/intermediate/stage5.bo: src//stage5.bsv /opt/tools/bsc/latest//lib/Libraries/FIFOF.bo /opt/tools/bsc/latest//lib/Libraries/Vector.bo /opt/tools/bsc/latest//lib/Libraries/SpecialFIFOs.bo /opt/tools/bsc/latest//lib/Libraries/FIFOF.bo build/hw/intermediate/TxRx.bo /opt/tools/bsc/latest//lib/Libraries/DefaultValue.bo /opt/tools/bsc/latest//lib/Libraries/Assert.bo /opt/tools/bsc/latest//lib/Libraries/Connectable.bo build/hw/intermediate/pipe_ifcs.bo build/hw/intermediate/dcache_types.bo build/hw/intermediate/csrbox.bo build/hw/intermediate/csr_types.bo build/hw/intermediate/ccore_types.bo /opt/tools/bsc/latest//lib/Libraries/DReg.bo /opt/tools/bsc/latest//lib/Libraries/Prelude.bo /opt/tools/bsc/latest//lib/Libraries/PreludeBSV.bo src//trap.defines common_bsv//Logger.bsv
build/hw/intermediate/io_func.bo: test_soc//io_func.bsv /opt/tools/bsc/latest//lib/Libraries/Prelude.bo /opt/tools/bsc/latest//lib/Libraries/PreludeBSV.bo
build/hw/intermediate/icache.bo: caches_mmu/src/icache_1rw/icache.bsv /opt/tools/bsc/latest//lib/Libraries/FIFO.bo /opt/tools/bsc/latest//lib/Libraries/FIFOF.bo /opt/tools/bsc/latest//lib/Libraries/SpecialFIFOs.bo /opt/tools/bsc/latest//lib/Libraries/BRAMCore.bo /opt/tools/bsc/latest//lib/Libraries/Vector.bo /opt/tools/bsc/latest//lib/Libraries/GetPut.bo /opt/tools/bsc/latest//lib/Libraries/Assert.bo /opt/tools/bsc/latest//lib/Libraries/OInt.bo /opt/tools/bsc/latest//lib/Libraries/BUtils.bo /opt/tools/bsc/latest//lib/Libraries/Memory.bo /opt/tools/bsc/latest//lib/Libraries/DReg.bo /opt/tools/bsc/latest//lib/Libraries/UniqueWrappers.bo build/hw/intermediate/icache_types.bo build/hw/intermediate/icache_lib.bo build/hw/intermediate/replacement_icache.bo build/hw/intermediate/mem_config.bo build/hw/intermediate/common_tlb_types.bo build/hw/intermediate/ecc_hamming.bo build/hw/intermediate/io_func.bo build/hw/intermediate/pmp_func.bo /opt/tools/bsc/latest//lib/Libraries/Prelude.bo /opt/tools/bsc/latest//lib/Libraries/PreludeBSV.bo caches_mmu/src/icache_1rw/icache.defines common_bsv//Logger.bsv
build/hw/intermediate/fa_itlb.bo: caches_mmu/src/tlbs/fa_itlb.bsv /opt/tools/bsc/latest//lib/Libraries/FIFO.bo /opt/tools/bsc/latest//lib/Libraries/FIFOF.bo /opt/tools/bsc/latest//lib/Libraries/SpecialFIFOs.bo /opt/tools/bsc/latest//lib/Libraries/Vector.bo build/hw/intermediate/common_tlb_types.bo /opt/tools/bsc/latest//lib/Libraries/GetPut.bo /opt/tools/bsc/latest//lib/Libraries/Prelude.bo /opt/tools/bsc/latest//lib/Libraries/PreludeBSV.bo caches_mmu/src/tlbs/common_tlb.defines common_bsv//Logger.bsv
build/hw/intermediate/common_tlb_types.bo: caches_mmu/src/tlbs/common_tlb_types.bsv /opt/tools/bsc/latest//lib/Libraries/FIFO.bo /opt/tools/bsc/latest//lib/Libraries/FIFOF.bo /opt/tools/bsc/latest//lib/Libraries/SpecialFIFOs.bo /opt/tools/bsc/latest//lib/Libraries/Prelude.bo /opt/tools/bsc/latest//lib/Libraries/PreludeBSV.bo caches_mmu/src/tlbs/common_tlb.defines common_bsv//Logger.bsv
build/hw/intermediate/dcache1rw.bo: caches_mmu/src/dcache/dcache1rw.bsv /opt/tools/bsc/latest//lib/Libraries/FIFO.bo /opt/tools/bsc/latest//lib/Libraries/FIFOF.bo /opt/tools/bsc/latest//lib/Libraries/SpecialFIFOs.bo /opt/tools/bsc/latest//lib/Libraries/BRAMCore.bo /opt/tools/bsc/latest//lib/Libraries/Vector.bo /opt/tools/bsc/latest//lib/Libraries/GetPut.bo /opt/tools/bsc/latest//lib/Libraries/Assert.bo /opt/tools/bsc/latest//lib/Libraries/OInt.bo /opt/tools/bsc/latest//lib/Libraries/BUtils.bo /opt/tools/bsc/latest//lib/Libraries/Memory.bo /opt/tools/bsc/latest//lib/Libraries/DReg.bo /opt/tools/bsc/latest//lib/Libraries/UniqueWrappers.bo build/hw/intermediate/dcache_types.bo build/hw/intermediate/dcache_lib.bo build/hw/intermediate/replacement_dcache.bo build/hw/intermediate/common_tlb_types.bo build/hw/intermediate/pmp_func.bo build/hw/intermediate/io_func.bo /opt/tools/bsc/latest//lib/Libraries/Prelude.bo /opt/tools/bsc/latest//lib/Libraries/PreludeBSV.bo caches_mmu/src/dcache/dcache.defines common_bsv//Logger.bsv
build/hw/intermediate/fa_dtlb.bo: caches_mmu/src/tlbs/fa_dtlb.bsv /opt/tools/bsc/latest//lib/Libraries/FIFO.bo /opt/tools/bsc/latest//lib/Libraries/FIFOF.bo /opt/tools/bsc/latest//lib/Libraries/SpecialFIFOs.bo /opt/tools/bsc/latest//lib/Libraries/Vector.bo build/hw/intermediate/common_tlb_types.bo /opt/tools/bsc/latest//lib/Libraries/GetPut.bo /opt/tools/bsc/latest//lib/Libraries/Prelude.bo /opt/tools/bsc/latest//lib/Libraries/PreludeBSV.bo caches_mmu/src/tlbs/common_tlb.defines common_bsv//Logger.bsv
build/hw/intermediate/TxRx.bo: common_bsv//TxRx.bsv /opt/tools/bsc/latest//lib/Libraries/FIFOF.bo /opt/tools/bsc/latest//lib/Libraries/GetPut.bo /opt/tools/bsc/latest//lib/Libraries/Connectable.bo /opt/tools/bsc/latest//lib/Libraries/Prelude.bo /opt/tools/bsc/latest//lib/Libraries/PreludeBSV.bo
build/hw/intermediate/combo.bo: src/mbox/combo.bsv /opt/tools/bsc/latest//lib/Libraries/FIFOF.bo /opt/tools/bsc/latest//lib/Libraries/Vector.bo /opt/tools/bsc/latest//lib/Libraries/SpecialFIFOs.bo build/hw/intermediate/signedmul.bo build/hw/intermediate/ccore_types.bo /opt/tools/bsc/latest//lib/Libraries/Prelude.bo /opt/tools/bsc/latest//lib/Libraries/PreludeBSV.bo common_bsv//Logger.bsv
build/hw/intermediate/restoring_div.bo: src/mbox/restoring_div.bsv build/hw/intermediate/ccore_types.bo /opt/tools/bsc/latest//lib/Libraries/Assert.bo /opt/tools/bsc/latest//lib/Libraries/DReg.bo /opt/tools/bsc/latest//lib/Libraries/FIFOF.bo /opt/tools/bsc/latest//lib/Libraries/ConfigReg.bo /opt/tools/bsc/latest//lib/Libraries/Prelude.bo /opt/tools/bsc/latest//lib/Libraries/PreludeBSV.bo src//trap.defines common_bsv//Logger.bsv
build/hw/intermediate/fpu_bsvfloat.bo: src/fpu/bsv_float/fpu_bsvfloat.bsv build/hw/intermediate/ccore_types.bo build/hw/intermediate/fpu_compare_min_max.bo build/hw/intermediate/fpu_int_to_sp.bo build/hw/intermediate/fpu_sign_injection.bo build/hw/intermediate/fpu_divider.bo build/hw/intermediate/fpu_sqrt.bo build/hw/intermediate/fpu_sp_to_int.bo build/hw/intermediate/fpu_dp_to_int.bo build/hw/intermediate/fpu_int_to_dp.bo build/hw/intermediate/fpu_fm_add_sub.bo build/hw/intermediate/fpu_convert_sp_dp.bo build/hw/intermediate/fpu_fclass.bo /opt/tools/bsc/latest//lib/Libraries/FIFO.bo /opt/tools/bsc/latest//lib/Libraries/FIFOF.bo /opt/tools/bsc/latest//lib/Libraries/SpecialFIFOs.bo build/hw/intermediate/TxRx.bo /opt/tools/bsc/latest//lib/Libraries/DReg.bo /opt/tools/bsc/latest//lib/Libraries/UniqueWrappers.bo /opt/tools/bsc/latest//lib/Libraries/Clocks.bo /opt/tools/bsc/latest//lib/Libraries/Prelude.bo /opt/tools/bsc/latest//lib/Libraries/PreludeBSV.bo src//trap.defines common_bsv//Logger.bsv src/fpu//fpu.defines src//ccore_params.defines
build/hw/intermediate/gshare_fa.bo: src/predictors/gshare_fa.bsv /opt/tools/bsc/latest//lib/Libraries/Assert.bo /opt/tools/bsc/latest//lib/Libraries/ConfigReg.bo /opt/tools/bsc/latest//lib/Libraries/Vector.bo /opt/tools/bsc/latest//lib/Libraries/OInt.bo /opt/tools/bsc/latest//lib/Libraries/RegFile.bo build/hw/intermediate/ccore_types.bo build/hw/intermediate/stack.bo /opt/tools/bsc/latest//lib/Libraries/Prelude.bo /opt/tools/bsc/latest//lib/Libraries/PreludeBSV.bo src//ccore_params.defines common_bsv//Logger.bsv
build/hw/intermediate/decompress.bo: src//decompress.bsv /opt/tools/bsc/latest//lib/Libraries/Prelude.bo /opt/tools/bsc/latest//lib/Libraries/PreludeBSV.bo
build/hw/intermediate/registerfile.bo: src//registerfile.bsv build/hw/intermediate/ccore_types.bo /opt/tools/bsc/latest//lib/Libraries/RegFile.bo /opt/tools/bsc/latest//lib/Libraries/Prelude.bo /opt/tools/bsc/latest//lib/Libraries/PreludeBSV.bo common_bsv//Logger.bsv
build/hw/intermediate/decoder.bo: src//decoder.bsv build/hw/intermediate/ccore_types.bo /opt/tools/bsc/latest//lib/Libraries/BUtils.bo build/hw/intermediate/csr_types.bo build/hw/intermediate/csrbox_decoder.bo /opt/tools/bsc/latest//lib/Libraries/Prelude.bo /opt/tools/bsc/latest//lib/Libraries/PreludeBSV.bo csrbox_bsv//csrbox.defines src//trap.defines src//decoder.defines
build/hw/intermediate/base_alu.bo: src//base_alu.bsv /opt/tools/bsc/latest//lib/Libraries/FIFOF.bo /opt/tools/bsc/latest//lib/Libraries/Vector.bo /opt/tools/bsc/latest//lib/Libraries/SpecialFIFOs.bo /opt/tools/bsc/latest//lib/Libraries/FIFOF.bo /opt/tools/bsc/latest//lib/Libraries/BUtils.bo build/hw/intermediate/ccore_types.bo /opt/tools/bsc/latest//lib/Libraries/Prelude.bo /opt/tools/bsc/latest//lib/Libraries/PreludeBSV.bo src//decoder.defines common_bsv//Logger.bsv
build/hw/intermediate/bypass.bo: src//bypass.bsv /opt/tools/bsc/latest//lib/Libraries/FIFOF.bo /opt/tools/bsc/latest//lib/Libraries/Vector.bo /opt/tools/bsc/latest//lib/Libraries/SpecialFIFOs.bo /opt/tools/bsc/latest//lib/Libraries/FIFOF.bo build/hw/intermediate/ccore_types.bo /opt/tools/bsc/latest//lib/Libraries/Prelude.bo /opt/tools/bsc/latest//lib/Libraries/PreludeBSV.bo common_bsv//Logger.bsv
build/hw/intermediate/icache_lib.bo: caches_mmu/src/icache_1rw/icache_lib.bsv /opt/tools/bsc/latest//lib/Libraries/FIFO.bo /opt/tools/bsc/latest//lib/Libraries/FIFOF.bo /opt/tools/bsc/latest//lib/Libraries/SpecialFIFOs.bo /opt/tools/bsc/latest//lib/Libraries/Vector.bo /opt/tools/bsc/latest//lib/Libraries/GetPut.bo /opt/tools/bsc/latest//lib/Libraries/Assert.bo /opt/tools/bsc/latest//lib/Libraries/OInt.bo /opt/tools/bsc/latest//lib/Libraries/BUtils.bo /opt/tools/bsc/latest//lib/Libraries/Memory.bo /opt/tools/bsc/latest//lib/Libraries/DReg.bo /opt/tools/bsc/latest//lib/Libraries/ConfigReg.bo build/hw/intermediate/io_func.bo build/hw/intermediate/ecc_hamming.bo build/hw/intermediate/mem_config.bo build/hw/intermediate/icache_types.bo /opt/tools/bsc/latest//lib/Libraries/Prelude.bo /opt/tools/bsc/latest//lib/Libraries/PreludeBSV.bo common_bsv//Logger.bsv
build/hw/intermediate/replacement_icache.bo: caches_mmu/src/icache_1rw/replacement_icache.bsv /opt/tools/bsc/latest//lib/Libraries/Vector.bo /opt/tools/bsc/latest//lib/Libraries/LFSR.bo /opt/tools/bsc/latest//lib/Libraries/Assert.bo /opt/tools/bsc/latest//lib/Libraries/Prelude.bo /opt/tools/bsc/latest//lib/Libraries/PreludeBSV.bo
build/hw/intermediate/mem_config.bo: common_verilog/bsvwrappers//mem_config.bsv /opt/tools/bsc/latest//lib/Libraries/BRAMCore.bo /opt/tools/bsc/latest//lib/Libraries/DReg.bo /opt/tools/bsc/latest//lib/Libraries/FIFOF.bo /opt/tools/bsc/latest//lib/Libraries/SpecialFIFOs.bo /opt/tools/bsc/latest//lib/Libraries/Assert.bo build/hw/intermediate/bram_1rw.bo build/hw/intermediate/bram_1r1w.bo build/hw/intermediate/bram_2rw.bo build/hw/intermediate/ecc_hamming.bo /opt/tools/bsc/latest//lib/Libraries/Prelude.bo /opt/tools/bsc/latest//lib/Libraries/PreludeBSV.bo common_bsv//Logger.bsv
build/hw/intermediate/ecc_hamming.bo: common_bsv//ecc_hamming.bsv /opt/tools/bsc/latest//lib/Libraries/Vector.bo /opt/tools/bsc/latest//lib/Libraries/LFSR.bo /opt/tools/bsc/latest//lib/Libraries/Prelude.bo /opt/tools/bsc/latest//lib/Libraries/PreludeBSV.bo common_bsv//Logger.bsv
build/hw/intermediate/pmp_func.bo: caches_mmu/src/pmp/pmp_func.bsv /opt/tools/bsc/latest//lib/Libraries/Vector.bo /opt/tools/bsc/latest//lib/Libraries/Reserved.bo /opt/tools/bsc/latest//lib/Libraries/Prelude.bo /opt/tools/bsc/latest//lib/Libraries/PreludeBSV.bo common_bsv//Logger.bsv
build/hw/intermediate/dcache_lib.bo: caches_mmu/src/dcache/dcache_lib.bsv /opt/tools/bsc/latest//lib/Libraries/FIFO.bo /opt/tools/bsc/latest//lib/Libraries/FIFOF.bo /opt/tools/bsc/latest//lib/Libraries/SpecialFIFOs.bo /opt/tools/bsc/latest//lib/Libraries/Vector.bo /opt/tools/bsc/latest//lib/Libraries/GetPut.bo /opt/tools/bsc/latest//lib/Libraries/Assert.bo /opt/tools/bsc/latest//lib/Libraries/OInt.bo /opt/tools/bsc/latest//lib/Libraries/BUtils.bo /opt/tools/bsc/latest//lib/Libraries/Memory.bo /opt/tools/bsc/latest//lib/Libraries/DReg.bo /opt/tools/bsc/latest//lib/Libraries/ConfigReg.bo build/hw/intermediate/io_func.bo build/hw/intermediate/ecc_hamming.bo build/hw/intermediate/mem_config.bo build/hw/intermediate/dcache_types.bo /opt/tools/bsc/latest//lib/Libraries/Prelude.bo /opt/tools/bsc/latest//lib/Libraries/PreludeBSV.bo common_bsv//Logger.bsv
build/hw/intermediate/replacement_dcache.bo: caches_mmu/src/dcache/replacement_dcache.bsv /opt/tools/bsc/latest//lib/Libraries/Vector.bo /opt/tools/bsc/latest//lib/Libraries/LFSR.bo /opt/tools/bsc/latest//lib/Libraries/Assert.bo /opt/tools/bsc/latest//lib/Libraries/Prelude.bo /opt/tools/bsc/latest//lib/Libraries/PreludeBSV.bo
build/hw/intermediate/signedmul.bo: common_verilog/bsvwrappers//signedmul.bsv /opt/tools/bsc/latest//lib/Libraries/Prelude.bo /opt/tools/bsc/latest//lib/Libraries/PreludeBSV.bo
build/hw/intermediate/fpu_compare_min_max.bo: src/fpu/bsv_float/fpu_compare_min_max.bsv build/hw/intermediate/ccore_types.bo /opt/tools/bsc/latest//lib/Libraries/Prelude.bo /opt/tools/bsc/latest//lib/Libraries/PreludeBSV.bo src/fpu//fpu.defines src//ccore_params.defines
build/hw/intermediate/fpu_int_to_sp.bo: src/fpu/bsv_float/fpu_int_to_sp.bsv build/hw/intermediate/ccore_types.bo /opt/tools/bsc/latest//lib/Libraries/UniqueWrappers.bo /opt/tools/bsc/latest//lib/Libraries/Prelude.bo /opt/tools/bsc/latest//lib/Libraries/PreludeBSV.bo src/fpu//fpu.defines src//ccore_params.defines
build/hw/intermediate/fpu_sign_injection.bo: src/fpu/bsv_float/fpu_sign_injection.bsv build/hw/intermediate/ccore_types.bo /opt/tools/bsc/latest//lib/Libraries/Prelude.bo /opt/tools/bsc/latest//lib/Libraries/PreludeBSV.bo src/fpu//fpu.defines src//ccore_params.defines
build/hw/intermediate/fpu_divider.bo: src/fpu/bsv_float/fpu_divider.bsv /opt/tools/bsc/latest//lib/Libraries/DReg.bo build/hw/intermediate/ccore_types.bo build/hw/intermediate/integer_divider.bo /opt/tools/bsc/latest//lib/Libraries/RegFile.bo /opt/tools/bsc/latest//lib/Libraries/Prelude.bo /opt/tools/bsc/latest//lib/Libraries/PreludeBSV.bo src/fpu//fpu.defines src//ccore_params.defines
build/hw/intermediate/fpu_sqrt.bo: src/fpu/bsv_float/fpu_sqrt.bsv build/hw/intermediate/ccore_types.bo /opt/tools/bsc/latest//lib/Libraries/RegFile.bo /opt/tools/bsc/latest//lib/Libraries/FIFO.bo /opt/tools/bsc/latest//lib/Libraries/ConfigReg.bo /opt/tools/bsc/latest//lib/Libraries/DReg.bo /opt/tools/bsc/latest//lib/Libraries/Prelude.bo /opt/tools/bsc/latest//lib/Libraries/PreludeBSV.bo src/fpu//fpu.defines src//ccore_params.defines
build/hw/intermediate/fpu_sp_to_int.bo: src/fpu/bsv_float/fpu_sp_to_int.bsv build/hw/intermediate/ccore_types.bo /opt/tools/bsc/latest//lib/Libraries/UniqueWrappers.bo /opt/tools/bsc/latest//lib/Libraries/Prelude.bo /opt/tools/bsc/latest//lib/Libraries/PreludeBSV.bo src/fpu//fpu.defines src//ccore_params.defines
build/hw/intermediate/fpu_dp_to_int.bo: src/fpu/bsv_float/fpu_dp_to_int.bsv build/hw/intermediate/ccore_types.bo /opt/tools/bsc/latest//lib/Libraries/UniqueWrappers.bo /opt/tools/bsc/latest//lib/Libraries/Prelude.bo /opt/tools/bsc/latest//lib/Libraries/PreludeBSV.bo src/fpu//fpu.defines src//ccore_params.defines
build/hw/intermediate/fpu_int_to_dp.bo: src/fpu/bsv_float/fpu_int_to_dp.bsv build/hw/intermediate/ccore_types.bo /opt/tools/bsc/latest//lib/Libraries/UniqueWrappers.bo /opt/tools/bsc/latest//lib/Libraries/Prelude.bo /opt/tools/bsc/latest//lib/Libraries/PreludeBSV.bo src/fpu//fpu.defines src//ccore_params.defines
build/hw/intermediate/fpu_fm_add_sub.bo: src/fpu/bsv_float/fpu_fm_add_sub.bsv /opt/tools/bsc/latest//lib/Libraries/DReg.bo build/hw/intermediate/ccore_types.bo /opt/tools/bsc/latest//lib/Libraries/RegFile.bo /opt/tools/bsc/latest//lib/Libraries/UniqueWrappers.bo /opt/tools/bsc/latest//lib/Libraries/ConfigReg.bo /opt/tools/bsc/latest//lib/Libraries/Prelude.bo /opt/tools/bsc/latest//lib/Libraries/PreludeBSV.bo src/fpu//fpu.defines src//ccore_params.defines
build/hw/intermediate/fpu_convert_sp_dp.bo: src/fpu/bsv_float/fpu_convert_sp_dp.bsv build/hw/intermediate/ccore_types.bo /opt/tools/bsc/latest//lib/Libraries/UniqueWrappers.bo /opt/tools/bsc/latest//lib/Libraries/Prelude.bo /opt/tools/bsc/latest//lib/Libraries/PreludeBSV.bo src/fpu//fpu.defines src//ccore_params.defines
build/hw/intermediate/fpu_fclass.bo: src/fpu/bsv_float/fpu_fclass.bsv build/hw/intermediate/ccore_types.bo /opt/tools/bsc/latest//lib/Libraries/Prelude.bo /opt/tools/bsc/latest//lib/Libraries/PreludeBSV.bo src/fpu//fpu.defines src//ccore_params.defines
build/hw/intermediate/stack.bo: common_bsv//stack.bsv /opt/tools/bsc/latest//lib/Libraries/RegFile.bo /opt/tools/bsc/latest//lib/Libraries/Prelude.bo /opt/tools/bsc/latest//lib/Libraries/PreludeBSV.bo
build/hw/intermediate/bram_1rw.bo: common_verilog/bsvwrappers//bram_1rw.bsv /opt/tools/bsc/latest//lib/Libraries/Prelude.bo /opt/tools/bsc/latest//lib/Libraries/PreludeBSV.bo
build/hw/intermediate/bram_1r1w.bo: common_verilog/bsvwrappers//bram_1r1w.bsv /opt/tools/bsc/latest//lib/Libraries/Prelude.bo /opt/tools/bsc/latest//lib/Libraries/PreludeBSV.bo
build/hw/intermediate/bram_2rw.bo: common_verilog/bsvwrappers//bram_2rw.bsv /opt/tools/bsc/latest//lib/Libraries/Prelude.bo /opt/tools/bsc/latest//lib/Libraries/PreludeBSV.bo
build/hw/intermediate/integer_divider.bo: src/fpu/bsv_float/integer_divider.bsv /opt/tools/bsc/latest//lib/Libraries/UniqueWrappers.bo /opt/tools/bsc/latest//lib/Libraries/Prelude.bo /opt/tools/bsc/latest//lib/Libraries/PreludeBSV.bo
